import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "./components";

// import { instrument } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={instrument.className}
      >
        <Header />
        <main>{children}</main>
        <Footer />
        <div id="modal-root" />
      </body>
    </html>
  );
}
